# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: ":seedling:"
  labels:
    - "dependabot"
# Main Go module
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
  ## group all dependencies with a k8s.io prefix into a single PR.
  groups:
    kubernetes:
      patterns: [ "k8s.io/*" ]
  commit-message:
    prefix: ":seedling:"
  labels:
    - "dependabot"
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: ":seedling:"
  labels:
    - "dependabot"
